# Ruff configuration file
# Step 0.9: Updated configuration with new lint section format

target-version = "py311"
line-length = 88

# Linting configuration
[lint]
# Select rules as specified in step 0.6
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
]

# Ignore specific rules
ignore = [
    "E501",  # line too long, handled by formatter
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

# Enable auto-fixing
fixable = ["ALL"]

# Per-file ignores
[lint.per-file-ignores]
"__init__.py" = ["F401"]

# Formatting configuration
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
